version: "3"
services:
  nginx:
    ports:
      - "80:80"
  workout-planner:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
      - REDIS_URL=${REDIS_URL}
      - REDIS_PORT=${REDIS_PORT}
      - MONGO_URI=${MONGO_URI}
      - MONGO_PORT=${MONGO_PORT}
    command: node index.js